version: '3.8'

services:
  db:
    image: postgres:15
    container_name: ecommerce_postgres
    environment:
      POSTGRES_USER: zee
      POSTGRES_PASSWORD: Zcanucks83
      POSTGRES_DB: ecommerce_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: 